# Generated by Django 5.2.4 on 2025-09-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Учитель'), ('student', 'Ученик')], default='admin', max_length=10),
        ),
    ]
