# Generated by Django 5.2.4 on 2025-09-20 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='student_groups', through='users.UserGroup', to=settings.AUTH_USER_MODEL),
        ),
    ]
