# Generated by Django 5.2.4 on 2025-11-05 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0004_alter_task_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название варианта')),
                ('task_type', models.CharField(blank=True, choices=[('1', '1. Анализ информационных моделей'), ('2', '2. Построение таблиц истинности логических выражений'), ('3', '3. Поиск информации в реляционных базах данных'), ('4', '4. Кодирование и декодирование данных. Условие Фано'), ('5', '5. Анализ алгоритмов для исполнителей'), ('6', '6. Циклические алгоритмы для исполнителя'), ('7', '7. Кодирование графической и звуковой информации'), ('8', '8. Комбинаторика'), ('9', '9. Обработка числовой информации в электронных таблицах'), ('10', '10. Поиск слова в текстовом документе'), ('11', '11. Вычисление количества информации'), ('12', '12. Алгоритмы для исполнителей с циклами и ветвлениями'), ('13', '13. IP адресация'), ('14', '14. Позиционные системы счисления'), ('15', '15. Истинность логического выражения'), ('16', '16. Вычисление значения рекурсивной функции'), ('17', '17. Обработка целочисленных данных'), ('18', '18. Робот-сборщик монет'), ('19-21', '19-21. Теория игр'), ('1921', '19-21. Теория игр'), ('22', '22. Многопоточные вычисления'), ('23', '23. Динамическое программирование. Количество программ'), ('24', '24. Обработка тестовых файлов'), ('25', '25. Обработка целочисленных данных. Поиск делителей'), ('26', '26. Обработка данных с помощью сортировки'), ('27', '27. Анализ данных. Кластеризация')], max_length=10, null=True, verbose_name='Тип задания')),
                ('variant_type', models.CharField(choices=[('closed', 'Закрытый (показывает правильность, но не ответ)'), ('open', 'Открытый (показывает ответ после завершения)')], default='closed', max_length=10, verbose_name='Тип варианта')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ограничение по времени (в минутах)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_variants', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VariantTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_tasks', to='tasks.task', verbose_name='Задание')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_tasks', to='variants.variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Задание варианта',
                'verbose_name_plural': 'Задания вариантов',
                'ordering': ['order'],
                'unique_together': {('variant', 'task')},
            },
        ),
        migrations.AddField(
            model_name='variant',
            name='tasks',
            field=models.ManyToManyField(related_name='variants', through='variants.VariantTask', to='tasks.task', verbose_name='Задания'),
        ),
        migrations.CreateModel(
            name='VariantExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('timeout', 'Завершено по времени')], default='not_started', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('answers', models.JSONField(default=dict, verbose_name='Ответы')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_executions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='variants.variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Выполнение варианта',
                'verbose_name_plural': 'Выполнения вариантов',
                'ordering': ['-started_at'],
                'unique_together': {('variant', 'student')},
            },
        ),
    ]
