# Generated by Django 5.2.4 on 2025-11-06 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='variantexecution',
            name='current_task_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Текущее задание'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant_type',
            field=models.CharField(choices=[('normal', 'Обычный'), ('control', 'Контроль')], default='normal', max_length=10, verbose_name='Тип варианта'),
        ),
        migrations.CreateModel(
            name='VariantAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_variants', to=settings.AUTH_USER_MODEL, verbose_name='Назначено')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='variants.variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Назначение варианта',
                'verbose_name_plural': 'Назначения вариантов',
                'ordering': ['-assigned_at'],
                'unique_together': {('variant', 'student')},
            },
        ),
    ]
