# Generated by Django 5.2.4 on 2025-11-05 15:59

from django.db import migrations


def convert_closed_to_normal(apps, schema_editor):
    """Преобразует все старые значения 'closed' в 'normal' (Обычный)"""
    Variant = apps.get_model('variants', 'Variant')
    Variant.objects.filter(variant_type='closed').update(variant_type='normal')


def reverse_convert(apps, schema_editor):
    """Обратное преобразование (для отката миграции)"""
    Variant = apps.get_model('variants', 'Variant')
    Variant.objects.filter(variant_type='normal').update(variant_type='closed')


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0002_variantexecution_current_task_order_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_closed_to_normal, reverse_convert),
    ]
