# Generated by Django 5.2.4 on 2025-11-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0003_convert_closed_to_normal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variantassignment',
            unique_together=set(),
        ),
    ]
