# Generated by Django 5.2.4 on 2025-11-06 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0004_remove_unique_constraint_from_assignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variantexecution',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='variantexecution',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='variants.variantassignment', verbose_name='Назначение'),
        ),
    ]
