# Generated by Django 5.2.4 on 2025-09-20 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('tasks', '0003_importsession_task_import_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в уроке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_lesson_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_tasks', to='courses.lesson', verbose_name='Урок')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_tasks', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Задание в уроке',
                'verbose_name_plural': 'Задания в уроках',
                'ordering': ['lesson', 'order', 'created_at'],
                'unique_together': {('lesson', 'task')},
            },
        ),
    ]
