# Generated by Django 5.2.4 on 2025-09-20 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lessontask'),
        ('users', '0002_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительные инструкции')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='users.group', verbose_name='Группа')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Назначение урока',
                'verbose_name_plural': 'Назначения уроков',
                'ordering': ['-assigned_at'],
                'unique_together': {('lesson', 'group')},
            },
        ),
    ]
