# Generated by Django 5.2.4 on 2025-09-20 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessonassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название блока')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание блока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в курсе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Блок курса',
                'verbose_name_plural': 'Блоки курса',
                'ordering': ['order', 'created_at'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.courseblock', verbose_name='Блок курса'),
        ),
    ]
