# Generated by Django 5.2.4 on 2025-09-21 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseblock_lesson_block'),
        ('tasks', '0003_importsession_task_import_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Задан'), ('in_progress', 'Выполняется'), ('completed', 'Завершен')], default='assigned', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начал выполнение')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершил выполнение')),
                ('current_task_index', models.IntegerField(default=0, verbose_name='Текущее задание')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='courses.lessonassignment', verbose_name='Назначение')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='courses.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_executions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Выполнение урока',
                'verbose_name_plural': 'Выполнения уроков',
                'ordering': ['-started_at'],
                'unique_together': {('lesson', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ ученика')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.lessonexecution', verbose_name='Выполнение урока')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Ответ на задание',
                'verbose_name_plural': 'Ответы на задания',
                'ordering': ['-answered_at'],
                'unique_together': {('execution', 'task')},
            },
        ),
    ]
