# Generated by Django 5.2.4 on 2025-09-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessonexecution_taskanswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonassignment',
            unique_together=set(),
        ),
    ]
