# Generated by Django 5.2.4 on 2025-09-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_unique_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonexecution',
            unique_together=set(),
        ),
    ]
