# Generated by Django 5.2.4 on 2025-09-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_execution_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonexecution',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='lessonexecution',
            name='status',
            field=models.CharField(choices=[('assigned', 'Задан'), ('in_progress', 'Выполняется'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='assigned', max_length=20, verbose_name='Статус'),
        ),
    ]
