# Generated by Django 5.2.4 on 2025-09-21 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lessonexecution_is_active_and_more'),
        ('tasks', '0004_alter_task_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='task_pool',
            field=models.ManyToManyField(blank=True, related_name='control_lessons', to='tasks.task', verbose_name='Пул заданий для вариантов'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tasks_per_variant',
            field=models.PositiveIntegerField(default=0, verbose_name='Заданий в варианте'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='variants_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество вариантов'),
        ),
        migrations.CreateModel(
            name='ControlVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_number', models.PositiveIntegerField(verbose_name='Номер варианта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_variants', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Вариант контрольной работы',
                'verbose_name_plural': 'Варианты контрольных работ',
                'ordering': ['variant_number'],
                'unique_together': {('lesson', 'variant_number')},
            },
        ),
        migrations.CreateModel(
            name='ControlVariantAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('lesson_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_assignments', to='courses.lessonassignment', verbose_name='Назначение урока')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_variant_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='courses.controlvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Назначение варианта',
                'verbose_name_plural': 'Назначения вариантов',
                'ordering': ['-assigned_at'],
                'unique_together': {('lesson_assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ControlVariantTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в варианте')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_assignments', to='tasks.task', verbose_name='Задание')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_tasks', to='courses.controlvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Задание варианта',
                'verbose_name_plural': 'Задания вариантов',
                'ordering': ['order'],
                'unique_together': {('variant', 'task')},
            },
        ),
    ]
