# Generated by Django 5.2.4 on 2025-09-19 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст задания')),
                ('task_type', models.CharField(choices=[('1', '1. Анализ информационных моделей'), ('2', '2. Построение таблиц истинности логических выражений'), ('3', '3. Поиск информации в реляционных базах данных'), ('4', '4. Кодирование и декодирование данных. Условие Фано'), ('5', '5. Анализ алгоритмов для исполнителей'), ('6', '6. Циклические алгоритмы для исполнителя'), ('7', '7. Кодирование графической и звуковой информации'), ('8', '8. Комбинаторика'), ('9', '9. Обработка числовой информации в электронных таблицах'), ('10', '10. Поиск слова в текстовом документе'), ('11', '11. Вычисление количества информации'), ('12', '12. Алгоритмы для исполнителей с циклами и ветвлениями'), ('13', '13. IP адресация'), ('14', '14. Позиционные системы счисления'), ('15', '15. Истинность логического выражения'), ('16', '16. Вычисление значения рекурсивной функции'), ('17', '17. Обработка целочисленных данных'), ('18', '18. Робот-сборщик монет'), ('19-21', '19-21. Теория игр'), ('1921', '19-21. Теория игр'), ('22', '22. Многопоточные вычисления'), ('23', '23. Динамическое программирование. Количество программ'), ('24', '24. Обработка тестовых файлов'), ('25', '25. Обработка целочисленных данных. Поиск делителей'), ('26', '26. Обработка данных с помощью сортировки'), ('27', '27. Анализ данных. Кластеризация')], max_length=10, verbose_name='Тип задания')),
                ('subtype', models.CharField(max_length=20, verbose_name='Подтип задания')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Сложная')], default='easy', max_length=10, verbose_name='Сложность')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tasks/images/', verbose_name='Изображение')),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks/files/', verbose_name='Файл для решения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
    ]
