# Generated by Django 5.2.4 on 2025-09-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_html',
            field=models.BooleanField(default=False, verbose_name='HTML разметка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtype',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Подтип задания'),
        ),
    ]
