# Generated by Django 5.2.4 on 2025-09-20 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_html_alter_task_subtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID сессии')),
                ('name', models.CharField(max_length=200, verbose_name='Название сессии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('task_type', models.CharField(choices=[('1', '1. Анализ информационных моделей'), ('2', '2. Построение таблиц истинности логических выражений'), ('3', '3. Поиск информации в реляционных базах данных'), ('4', '4. Кодирование и декодирование данных. Условие Фано'), ('5', '5. Анализ алгоритмов для исполнителей'), ('6', '6. Циклические алгоритмы для исполнителя'), ('7', '7. Кодирование графической и звуковой информации'), ('8', '8. Комбинаторика'), ('9', '9. Обработка числовой информации в электронных таблицах'), ('10', '10. Поиск слова в текстовом документе'), ('11', '11. Вычисление количества информации'), ('12', '12. Алгоритмы для исполнителей с циклами и ветвлениями'), ('13', '13. IP адресация'), ('14', '14. Позиционные системы счисления'), ('15', '15. Истинность логического выражения'), ('16', '16. Вычисление значения рекурсивной функции'), ('17', '17. Обработка целочисленных данных'), ('18', '18. Робот-сборщик монет'), ('19-21', '19-21. Теория игр'), ('1921', '19-21. Теория игр'), ('22', '22. Многопоточные вычисления'), ('23', '23. Динамическое программирование. Количество программ'), ('24', '24. Обработка тестовых файлов'), ('25', '25. Обработка целочисленных данных. Поиск делителей'), ('26', '26. Обработка данных с помощью сортировки'), ('27', '27. Анализ данных. Кластеризация')], max_length=10, verbose_name='Тип заданий')),
                ('subtype', models.CharField(blank=True, max_length=20, null=True, verbose_name='Подтип заданий')),
                ('tasks_count', models.PositiveIntegerField(default=0, verbose_name='Количество заданий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Сессия импорта',
                'verbose_name_plural': 'Сессии импорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.importsession', verbose_name='Сессия импорта'),
        ),
    ]
