# Generated by Django 5.2.4 on 2025-09-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_importsession_task_import_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
    ]
